// web/portal/src/pages/usercenter/index.tsx
/** Author: Charlie */

import { useMemo, type ReactNode } from 'react'
import { Menu } from 'antd'
import type { MenuProps } from 'antd'
import {
  DeleteOutlined,
  LockOutlined,
  MailOutlined,
  MessageOutlined,
  MobileOutlined,
  UserOutlined,
  ApiOutlined,
} from '@ant-design/icons'
import { useSearchParams } from 'react-router-dom'
import { useAuthStore } from '@/stores/auth'
import { BasicInfoPanel } from './components/BasicInfoPanel'
import { CancelAccountPanel } from './components/CancelAccountPanel'
import { EmailPanel } from './components/EmailPanel'
import { MyMessagesPanel } from './components/MyMessagesPanel'
import { OauthPanel } from './components/OauthPanel'
import { PasswordPanel } from './components/PasswordPanel'
import { PhonePanel } from './components/PhonePanel'
import './usercenter.css'

const NAV_ITEMS = [
  { key: 'basic_info', label: '公开资料' },
  { key: 'my_messages', label: '我的消息' },
  { key: 'password', label: '密码' },
  { key: 'phone', label: '手机号' },
  { key: 'email', label: '邮箱' },
  { key: 'oauth', label: '三方账号' },
  { key: 'cancel_account', label: '账号注销' },
] as const

type TabKey = (typeof NAV_ITEMS)[number]['key']

const PANEL_MAP: Record<TabKey, ReactNode> = {
  basic_info: <BasicInfoPanel />,
  my_messages: <MyMessagesPanel />,
  password: <PasswordPanel />,
  phone: <PhonePanel />,
  email: <EmailPanel />,
  oauth: <OauthPanel />,
  cancel_account: <CancelAccountPanel />,
}

function resolveTab(tab: string | null): TabKey {
  if (tab && NAV_ITEMS.some((item) => item.key === tab)) {
    return tab as TabKey
  }
  return 'basic_info'
}

export function UserCenterPage() {
  const [searchParams, setSearchParams] = useSearchParams()
  const userInfo = useAuthStore((s) => s.userInfo)
  const activeTab = resolveTab(searchParams.get('tab'))
  const activeNav = NAV_ITEMS.find((item) => item.key === activeTab) ?? NAV_ITEMS[0]

  const lockedTabs = useMemo(() => {
    if (userInfo?.passwordExpired) return new Set<TabKey>(['password'])
    const allowed = new Set<TabKey>()
    if (userInfo?.forceBindEmail) allowed.add('email')
    if (userInfo?.forceBindPhone) allowed.add('phone')
    return allowed.size > 0 ? allowed : null
  }, [userInfo])

  const menuItems: MenuProps['items'] = useMemo(
    () => [
      {
        key: 'basic_info',
        icon: <UserOutlined />,
        label: '公开资料',
        disabled: Boolean(lockedTabs && !lockedTabs.has('basic_info')),
      },
      {
        type: 'group',
        label: '消息',
        children: [
          {
            key: 'my_messages',
            icon: <MessageOutlined />,
            label: '我的消息',
            disabled: Boolean(lockedTabs && !lockedTabs.has('my_messages')),
          },
        ],
      },
      {
        type: 'group',
        label: '访问与安全',
        children: [
          {
            key: 'password',
            icon: <LockOutlined />,
            label: '密码',
            disabled: Boolean(lockedTabs && !lockedTabs.has('password')),
          },
          {
            key: 'phone',
            icon: <MobileOutlined />,
            label: '手机号',
            disabled: Boolean(lockedTabs && !lockedTabs.has('phone')),
          },
          {
            key: 'email',
            icon: <MailOutlined />,
            label: '邮箱',
            disabled: Boolean(lockedTabs && !lockedTabs.has('email')),
          },
          {
            key: 'oauth',
            icon: <ApiOutlined />,
            label: '三方账号',
            disabled: Boolean(lockedTabs && !lockedTabs.has('oauth')),
          },
          {
            key: 'cancel_account',
            icon: <DeleteOutlined />,
            label: '账号注销',
            danger: true,
            disabled: Boolean(lockedTabs && !lockedTabs.has('cancel_account')),
          },
        ],
      },
    ],
    [lockedTabs],
  )

  function selectTab(key: string) {
    if (!key || activeTab === key) return
    if (!NAV_ITEMS.some((item) => item.key === key)) return
    if (lockedTabs && !lockedTabs.has(key as TabKey)) return
    const next = new URLSearchParams(searchParams)
    next.set('tab', key)
    setSearchParams(next, { replace: true })
  }

  return (
    <div className="user-center page-shell w-full min-w-0">
      <div className="user-center__body">
        <aside className="user-center__sidebar">
          <Menu
            mode="inline"
            selectedKeys={[activeTab]}
            items={menuItems}
            onClick={({ key }) => selectTab(String(key))}
          />
        </aside>

        <section className="user-center__content">
          <div className="user-center__panel">
            <h2
              className={
                activeTab === 'basic_info'
                  ? 'user-center__panel-title user-center__panel-title--with-tabs'
                  : 'user-center__panel-title'
              }
            >
              {activeNav.label}
            </h2>
            {PANEL_MAP[activeTab]}
          </div>
        </section>
      </div>
    </div>
  )
}

// web/admin/src/views/usercenter/index.vue
<!-- Author: Charlie -->

<script setup lang="ts">
import type { MenuOption } from 'naive-ui'
import type { Component } from 'vue'
import { renderIcon } from '@/utils/icon'
import { computed, reactive, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useAuthStore } from '@/stores'
import './usercenter.css'
import BasicInfoPanel from './components/BasicInfoPanel.vue'
import CancelAccountPanel from './components/CancelAccountPanel.vue'
import EmailPanel from './components/EmailPanel.vue'
import MyMessagesPanel from './components/MyMessagesPanel.vue'
import PasswordPanel from './components/PasswordPanel.vue'
import PhonePanel from './components/PhonePanel.vue'
import OauthPanel from './components/OauthPanel.vue'

const route = useRoute()
const router = useRouter()
const authStore = useAuthStore()

const navItems: Array<{ key: string; label: string; icon: string }> = [
  { key: 'basic_info', label: '公开资料', icon: 'icon-park-outline:people' },
  { key: 'my_messages', label: '我的消息', icon: 'icon-park-outline:message' },
  { key: 'password', label: '密码', icon: 'icon-park-outline:lock' },
  { key: 'phone', label: '手机号', icon: 'icon-park-outline:phone-telephone' },
  { key: 'email', label: '邮箱', icon: 'icon-park-outline:mail' },
  { key: 'oauth', label: '三方账号', icon: 'icon-park-outline:people' },
  { key: 'cancel_account', label: '账号注销', icon: 'icon-park-outline:logout' },
]

const panelMap: Record<string, Component> = {
  basic_info: BasicInfoPanel,
  my_messages: MyMessagesPanel,
  password: PasswordPanel,
  phone: PhonePanel,
  email: EmailPanel,
  oauth: OauthPanel,
  cancel_account: CancelAccountPanel,
}

const state = reactive({
  loading: false,
  activeTab: resolveInitialTab(),
})

const lockedTabs = computed(() => {
  const user = authStore.userInfo
  if (user?.passwordExpired) return new Set(['password'])
  const allowed = new Set<string>()
  if (user?.forceBindEmail) allowed.add('email')
  if (user?.forceBindPhone) allowed.add('phone')
  return allowed.size > 0 ? allowed : null
})

const menuOptions = computed<MenuOption[]>(() => [
  {
    key: 'basic_info',
    label: '公开资料',
    icon: renderIcon('icon-park-outline:people', 16),
    disabled: Boolean(lockedTabs.value && !lockedTabs.value.has('basic_info')),
  },
  {
    type: 'group',
    label: '消息',
    key: 'messages',
    children: [
      {
        key: 'my_messages',
        label: '我的消息',
        icon: renderIcon('icon-park-outline:message', 16),
        disabled: Boolean(lockedTabs.value && !lockedTabs.value.has('my_messages')),
      },
    ],
  },
  {
    type: 'group',
    label: '访问与安全',
    key: 'access',
    children: [
      {
        key: 'password',
        label: '密码',
        icon: renderIcon('icon-park-outline:lock', 16),
        disabled: Boolean(lockedTabs.value && !lockedTabs.value.has('password')),
      },
      {
        key: 'phone',
        label: '手机号',
        icon: renderIcon('icon-park-outline:phone-telephone', 16),
        disabled: Boolean(lockedTabs.value && !lockedTabs.value.has('phone')),
      },
      {
        key: 'email',
        label: '邮箱',
        icon: renderIcon('icon-park-outline:mail', 16),
        disabled: Boolean(lockedTabs.value && !lockedTabs.value.has('email')),
      },
      {
        key: 'oauth',
        label: '三方账号',
        icon: renderIcon('icon-park-outline:people', 16),
        disabled: Boolean(lockedTabs.value && !lockedTabs.value.has('oauth')),
      },
      {
        key: 'cancel_account',
        label: '账号注销',
        icon: renderIcon('icon-park-outline:logout', 16),
        disabled: Boolean(lockedTabs.value && !lockedTabs.value.has('cancel_account')),
      },
    ],
  },
])

const activeNav = computed(
  () => navItems.find((item) => item.key === state.activeTab) ?? navItems[0],
)
const activePanel = computed(() => panelMap[state.activeTab] ?? BasicInfoPanel)

function resolveInitialTab() {
  const tab = typeof route.query.tab === 'string' ? route.query.tab : ''
  if (tab && navItems.some((item) => item.key === tab)) {
    return tab
  }
  return 'basic_info'
}

function selectTab(key: string) {
  if (!key || state.activeTab === key) {
    return
  }
  if (!navItems.some((item) => item.key === key)) {
    return
  }
  if (lockedTabs.value && !lockedTabs.value.has(key)) {
    return
  }
  state.activeTab = key
  void router.replace({ query: { ...route.query, tab: key } })
}

watch(
  () => route.query.tab,
  (tab) => {
    if (
      typeof tab === 'string' &&
      navItems.some((item) => item.key === tab) &&
      state.activeTab !== tab
    ) {
      state.activeTab = tab
    }
  },
)
</script>

<template>
  <div class="user-center w-full min-w-0">
    <NSpin :show="state.loading">
      <div class="user-center__body">
        <aside class="user-center__sidebar">
          <NMenu
            :value="state.activeTab"
            :options="menuOptions"
            :root-indent="12"
            :indent="18"
            @update:value="selectTab"
          />
        </aside>

        <section class="user-center__content">
          <div class="user-center__panel">
            <h2
              class="user-center__panel-title"
              :class="{ 'user-center__panel-title--with-tabs': state.activeTab === 'basic_info' }"
            >
              {{ activeNav.label }}
            </h2>

            <KeepAlive>
              <component
                :is="activePanel"
                :key="state.activeTab"
              />
            </KeepAlive>
          </div>
        </section>
      </div>
    </NSpin>
  </div>
</template>
