// web/admin/src/layouts/components/header/Notices.vue
<!-- Author: Charlie -->

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { messageApi } from '@/api'
import MessageDetailModal from '@/components/message/MessageDetailModal.vue'
import { useMessageUnreadStore } from '@/stores'
import { formatDateTime, wireBool } from '@/utils'
import NoticeList, { type BannerItem } from '../common/NoticeList.vue'
import { readPageMeta } from '@/utils/wire'

const pageSize = 8
const router = useRouter()

type LoadMode = 'replace' | 'merge' | 'append'
type NoticeKind = 'NOTIFICATION' | 'ANNOUNCEMENT'

interface NoticeSource {
  id: string
  title: string
  icon: string
  tagTitle?: string
  tagType?: BannerItem['tagType']
  description?: string
  date: string
  sourceType: NoticeKind
  sourceId: string
  isRead: boolean
}

const listState = reactive({
  records: [] as NoticeSource[],
  current: 0,
  size: pageSize,
  total: 0,
  loading: false,
  loaded: false,
})
const unreadStore = useMessageUnreadStore()
const showPopover = ref(false)
const detailModalRef = ref<InstanceType<typeof MessageDetailModal> | null>(null)

const list = computed(() => listState.records.map(toNoticeItem))
const hasMore = computed(() => listState.records.length < listState.total)
const unreadTotal = computed(() => unreadStore.unreadTotal)

onMounted(() => {
  void unreadStore.refresh()
})

async function refresh() {
  await Promise.all([unreadStore.refresh(), loadList(1, listState.loaded ? 'merge' : 'replace')])
}

async function loadMore() {
  if (listState.loading || listState.records.length >= listState.total) return
  await loadList(listState.current + 1, 'append')
}

async function loadList(page = 1, mode: LoadMode = 'replace') {
  if (listState.loading) return
  listState.loading = true
  try {
    const response = await messageApi.myPage({ current: page, size: listState.size })
    const data = response.data ?? {}
    const incoming = (data.records ?? []).map((item: any) => mapHistoryItem(item))
    listState.records = mergeNoticeRecords(listState.records, incoming, mode)
    const pageMeta = readPageMeta(data, { current: page, size: listState.size })
    listState.total = pageMeta.total || listState.records.length
    listState.current = pageMeta.current
    listState.size = pageMeta.size
    listState.loaded = true
  } finally {
    listState.loading = false
  }
}

async function handleOpen(id: string) {
  const item = listState.records.find((notice) => notice.id === id)
  if (!item) return
  await detailModalRef.value?.open({
    ...item,
    id: item.sourceId,
    sourceType: item.sourceType,
    is_read: item.isRead,
  })
}

function handleDetailChanged(payload: { type: string; id: string }) {
  const item = listState.records.find((notice) => notice.id === `${payload.type}:${payload.id}`)
  if (item) item.isRead = true
}

async function markAllRead() {
  try {
    await messageApi.readAll()
    listState.records.forEach((item) => {
      item.isRead = true
    })
    unreadStore.notifyReadAll()
  } catch {
    /* 忽略 */
  }
}

function goMore() {
  showPopover.value = false
  void router.push({ path: '/usercenter', query: { tab: 'my_messages' } })
}

function mergeNoticeRecords(
  current: NoticeSource[],
  incoming: NoticeSource[],
  mode: LoadMode,
): NoticeSource[] {
  if (mode === 'replace') return incoming
  const currentMap = new Map(current.map((item) => [item.id, item]))
  const result = current.map((item) => ({
    ...item,
    ...(incoming.find((i) => i.id === item.id) ?? {}),
  }))
  incoming.forEach((item) => {
    if (!currentMap.has(item.id)) result.push(item)
  })
  return result
}

function mapHistoryItem(item: any): NoticeSource {
  const kind: NoticeKind = item.kind === 'ANNOUNCEMENT' ? 'ANNOUNCEMENT' : 'NOTIFICATION'
  return {
    id: `${kind}:${item.id}`,
    title: item.title,
    icon:
      kind === 'ANNOUNCEMENT' ? 'icon-park-outline:volume-notice' : 'icon-park-outline:tips-one',
    tagTitle: kind === 'ANNOUNCEMENT' ? '公告' : '通知',
    tagType: kind === 'ANNOUNCEMENT' ? 'warning' : 'info',
    description: item.content,
    date: formatDateTime(item.publish_at || item.created_at),
    sourceType: kind,
    sourceId: item.id,
    isRead: wireBool(item.is_read ?? false),
  }
}

function toNoticeItem(item: NoticeSource): BannerItem {
  return { ...item, isRead: item.isRead } as BannerItem
}
</script>

<template>
  <n-popover
    v-model:show="showPopover"
    placement="bottom"
    trigger="click"
    arrow-point-to-center
    class="!p-0"
    @update:show="(show: boolean) => show && refresh()"
  >
    <template #trigger>
      <n-tooltip
        placement="bottom"
        trigger="hover"
      >
        <template #trigger>
          <CommonWrapper>
            <n-badge
              :value="unreadTotal"
              :max="99"
              style="color: unset"
            >
              <NovaIcon icon="icon-park-outline:remind" />
            </n-badge>
          </CommonWrapper>
        </template>
        消息
      </n-tooltip>
    </template>
    <NSpace
      vertical
      :size="0"
      style="width: 390px"
    >
      <div style="padding: 12px 12px 0; font-weight: 600">
        我的消息
      </div>
      <NoticeList
        :list="list"
        :loading="listState.loading"
        :has-more="hasMore"
        @open="handleOpen"
        @load-more="loadMore"
      />
      <NDivider style="margin: 0" />
      <div class="flex gap-2 p-2">
        <NButton
          class="flex-1"
          tertiary
          size="small"
          :disabled="unreadTotal <= 0"
          @click="markAllRead"
        >
          全部已读
        </NButton>
        <NButton
          class="flex-1"
          tertiary
          size="small"
          @click="goMore"
        >
          查看更多
        </NButton>
      </div>
    </NSpace>
  </n-popover>
  <MessageDetailModal
    ref="detailModalRef"
    @changed="handleDetailChanged"
  />
</template>

// web/portal/src/layouts/components/header/Notices.tsx
/** Author: Charlie */

import { useCallback, useEffect, useMemo, useState } from 'react'
import { Badge, Button, Divider, Popover, Tooltip } from 'antd'
import { BellOutlined } from '@ant-design/icons'
import { useNavigate } from 'react-router-dom'
import { messageApi } from '@/api'
import { formatDateTime, wireBool } from '@/utils'
import { readPageMeta } from '@/utils/wire'
import { useMessageUnreadStore } from '@/stores/messageUnread'
import {
  MessageDetailModal,
  type MessageDetailSource,
} from '@/components/message/MessageDetailModal'
import { NoticeList, type BannerItem } from '../common/NoticeList'

const pageSize = 8

type LoadMode = 'replace' | 'merge' | 'append'
type NoticeKind = 'NOTIFICATION' | 'ANNOUNCEMENT'

interface NoticeSource {
  id: string
  title: string
  icon: 'announcement' | 'notification'
  tagTitle?: string
  tagType?: BannerItem['tagType']
  description?: string
  date: string
  sourceType: NoticeKind
  sourceId: string
  isRead: boolean
}

function mapHistoryItem(item: any): NoticeSource {
  const kind: NoticeKind = item.kind === 'ANNOUNCEMENT' ? 'ANNOUNCEMENT' : 'NOTIFICATION'
  return {
    id: `${kind}:${item.id}`,
    title: item.title,
    icon: kind === 'ANNOUNCEMENT' ? 'announcement' : 'notification',
    tagTitle: kind === 'ANNOUNCEMENT' ? '公告' : '通知',
    tagType: kind === 'ANNOUNCEMENT' ? 'warning' : 'processing',
    description: item.content,
    date: formatDateTime(item.publish_at || item.created_at),
    sourceType: kind,
    sourceId: item.id,
    isRead: wireBool(item.is_read ?? false),
  }
}

function mergeNoticeRecords(
  current: NoticeSource[],
  incoming: NoticeSource[],
  mode: LoadMode,
): NoticeSource[] {
  if (mode === 'replace') return incoming
  const currentMap = new Map(current.map((item) => [item.id, item]))
  const result = current.map((item) => ({
    ...item,
    ...(incoming.find((i) => i.id === item.id) ?? {}),
  }))
  incoming.forEach((item) => {
    if (!currentMap.has(item.id)) result.push(item)
  })
  return result
}

export function Notices() {
  const navigate = useNavigate()
  const unreadTotal = useMessageUnreadStore((s) => s.unreadTotal)
  const refreshUnreadCount = useMessageUnreadStore((s) => s.refresh)
  const notifyReadAll = useMessageUnreadStore((s) => s.notifyReadAll)
  const [open, setOpen] = useState(false)
  const [records, setRecords] = useState<NoticeSource[]>([])
  const [current, setCurrent] = useState(0)
  const [total, setTotal] = useState(0)
  const [loading, setLoading] = useState(false)
  const [loaded, setLoaded] = useState(false)
  const [detailOpen, setDetailOpen] = useState(false)
  const [detailSource, setDetailSource] = useState<MessageDetailSource | null>(null)

  const list = useMemo(() => records.map((item) => ({ ...item }) as BannerItem), [records])
  const hasMore = records.length < total

  const loadList = useCallback(async (page = 1, mode: LoadMode = 'replace') => {
    setLoading(true)
    try {
      const response = await messageApi.myPage({ current: page, size: pageSize })
      const data = response.data ?? {}
      const incoming = (data.records ?? []).map((item: any) => mapHistoryItem(item))
      setRecords((prev) => mergeNoticeRecords(prev, incoming, mode))
      const pageMeta = readPageMeta(data, { current: page, size: pageSize })
      setTotal(pageMeta.total || incoming.length)
      setCurrent(pageMeta.current)
      setLoaded(true)
    } finally {
      setLoading(false)
    }
  }, [])

  const refresh = useCallback(async () => {
    await Promise.all([refreshUnreadCount(), loadList(1, loaded ? 'merge' : 'replace')])
  }, [loadList, loaded, refreshUnreadCount])

  useEffect(() => {
    void refreshUnreadCount()
  }, [refreshUnreadCount])

  async function loadMore() {
    if (loading || records.length >= total) return
    await loadList(current + 1, 'append')
  }

  function handleOpen(id: string) {
    const item = records.find((notice) => notice.id === id)
    if (!item) return
    setDetailSource({
      id: item.sourceId,
      sourceType: item.sourceType,
      title: item.title,
      content: item.description,
      is_read: item.isRead,
    })
    setDetailOpen(true)
  }

  function handleDetailChanged(payload: { type: string; id: string }) {
    setRecords((prev) =>
      prev.map((notice) =>
        notice.id === `${payload.type}:${payload.id}` ? { ...notice, isRead: true } : notice,
      ),
    )
  }

  async function markAllRead() {
    try {
      await messageApi.readAll()
      setRecords((prev) => prev.map((item) => ({ ...item, isRead: true })))
      notifyReadAll()
    } catch {
      /* ignore */
    }
  }

  function goMore() {
    setOpen(false)
    void navigate('/usercenter?tab=my_messages')
  }

  const content = (
    <div style={{ width: 390 }}>
      <div style={{ padding: '12px 12px 0', fontWeight: 600 }}>我的消息</div>
      <NoticeList
        list={list}
        loading={loading}
        hasMore={hasMore}
        onOpen={handleOpen}
        onLoadMore={() => void loadMore()}
      />
      <Divider style={{ margin: 0 }} />
      <div className="flex gap-2 p-2">
        <Button
          className="flex-1"
          size="small"
          type="text"
          disabled={unreadTotal <= 0}
          onClick={() => void markAllRead()}
        >
          全部已读
        </Button>
        <Button className="flex-1" size="small" type="text" onClick={goMore}>
          查看更多
        </Button>
      </div>
    </div>
  )

  return (
    <>
      <Popover
        content={content}
        trigger="click"
        open={open}
        onOpenChange={(next) => {
          setOpen(next)
          if (next) void refresh()
        }}
        placement="bottomRight"
        arrow={{ pointAtCenter: true }}
      >
        <Tooltip title="消息" placement="bottom">
          <button type="button" className="header-icon-btn" aria-label="消息">
            <Badge count={unreadTotal} overflowCount={99} size="small">
              <BellOutlined style={{ fontSize: 18 }} />
            </Badge>
          </button>
        </Tooltip>
      </Popover>

      <MessageDetailModal
        open={detailOpen}
        source={detailSource}
        onClose={() => {
          setDetailOpen(false)
          setDetailSource(null)
        }}
        onChanged={handleDetailChanged}
      />
    </>
  )
}
