// web/admin/src/views/usercenter/components/MessageFeedPanel.vue
<!-- Author: Charlie -->

<script setup lang="ts">
import { messageApi } from '@/api'
import MessageDetailModal from '@/components/message/MessageDetailModal.vue'
import { useMessageUnreadStore } from '@/stores'
import { dictTypeData, formatDateTime, wireBool } from '@/utils'
import { onMounted, reactive, ref } from 'vue'
import { readPageMeta } from '@/utils/wire'

const detailModalRef = ref<InstanceType<typeof MessageDetailModal> | null>(null)
const unreadStore = useMessageUnreadStore()
const state = reactive({
  rows: [] as any[],
  total: 0,
  loading: false,
  page: 1,
  pageSize: 10,
})

onMounted(() => {
  void fetchPage()
})

async function fetchPage() {
  state.loading = true
  try {
    const response = await messageApi.myPage({
      current: state.page,
      size: state.pageSize,
    })
    const data = response.data ?? {}
    state.rows = (data.records ?? []).map((row: any) => ({
      ...row,
      is_read: wireBool(row.is_read ?? false),
    }))
    const pageMeta = readPageMeta(data, { current: state.page, size: state.pageSize })
    state.total = pageMeta.total
    state.page = pageMeta.current
    state.pageSize = pageMeta.size
  } finally {
    state.loading = false
  }
}

function kindLabel(row: any) {
  return row.kind === 'ANNOUNCEMENT' ? '公告' : '通知'
}

function severityLabel(row: any) {
  if (!row.severity) return ''
  return dictTypeData('NOTIFICATION_SEVERITY', row.severity) || row.severity
}

function excerpt(row: any) {
  const text = String(row.content || '')
    .replace(/\s+/g, ' ')
    .trim()
  if (!text) return ''
  return text.length > 96 ? `${text.slice(0, 96)}…` : text
}

async function openDetail(row: any) {
  await detailModalRef.value?.open({
    id: row.id,
    sourceType: row.kind === 'ANNOUNCEMENT' ? 'ANNOUNCEMENT' : 'NOTIFICATION',
    title: row.title,
    is_read: row.is_read,
    publish_at: row.publish_at,
    content: row.content,
    severity: row.severity,
  })
}

async function handleDetailChanged(payload: { type: string; id: string }) {
  const row = state.rows.find((item) => item.id === payload.id)
  if (row) row.is_read = true
}

async function markAllRead() {
  await messageApi.readAll()
  state.rows.forEach((row) => {
    row.is_read = true
  })
  unreadStore.notifyReadAll()
  window.$message.success('已全部标记为已读')
}

function handlePageChange(page: number) {
  state.page = page
  void fetchPage()
}

function handlePageSizeChange(size: number) {
  state.pageSize = size
  state.page = 1
  void fetchPage()
}
</script>

<template>
  <NSpace
    vertical
    :size="12"
    class="w-full min-w-0"
  >
    <div class="flex justify-end gap-1">
      <NButton
        text
        :loading="state.loading"
        @click="fetchPage"
      >
        刷新
      </NButton>
      <NButton
        text
        @click="markAllRead"
      >
        全部已读
      </NButton>
    </div>

    <NSpin
      :show="state.loading"
      class="w-full min-w-0"
    >
      <NEmpty
        v-if="!state.loading && !state.rows.length"
        description="暂无消息"
      />
      <NList
        v-else
        clickable
        show-divider
        class="w-full min-w-0"
      >
        <NListItem
          v-for="row in state.rows"
          :key="row.id"
          @click="openDetail(row)"
        >
          <NThing class="w-full min-w-0">
            <template #avatar>
              <NBadge
                :dot="!row.is_read"
                type="info"
              >
                <NAvatar
                  round
                  :size="36"
                >
                  <NovaIcon
                    :icon="
                      row.kind === 'ANNOUNCEMENT'
                        ? 'icon-park-outline:volume-notice'
                        : 'icon-park-outline:tips-one'
                    "
                    :size="18"
                    :style="{ color: row.is_read ? 'var(--text-color-3)' : 'var(--primary-color)' }"
                  />
                </NAvatar>
              </NBadge>
            </template>
            <template #header>
              <NSpace
                :size="8"
                align="center"
                :wrap="true"
              >
                <NTag
                  size="small"
                  :bordered="false"
                  :type="row.kind === 'ANNOUNCEMENT' ? 'warning' : 'info'"
                >
                  {{ kindLabel(row) }}
                </NTag>
                <NTag
                  v-if="severityLabel(row)"
                  size="small"
                  :bordered="false"
                >
                  {{ severityLabel(row) }}
                </NTag>
                <NText
                  :depth="row.is_read ? 3 : 1"
                  :strong="!row.is_read"
                >
                  {{ row.title }}
                </NText>
              </NSpace>
            </template>
            <template #header-extra>
              <NText
                depth="3"
                style="font-size: 12px; white-space: nowrap"
              >
                {{ formatDateTime(row.publish_at || row.created_at) }}
              </NText>
            </template>
            <template
              v-if="excerpt(row)"
              #description
            >
              <NEllipsis
                :line-clamp="2"
                :tooltip="false"
              >
                <NText
                  depth="3"
                  style="font-size: 13px"
                >
                  {{ excerpt(row) }}
                </NText>
              </NEllipsis>
            </template>
          </NThing>
        </NListItem>
      </NList>
    </NSpin>

    <NSpace
      v-if="state.total > 0"
      justify="end"
    >
      <NPagination
        :page="state.page"
        :page-size="state.pageSize"
        :item-count="state.total"
        :page-sizes="[10, 20, 30]"
        show-size-picker
        @update:page="handlePageChange"
        @update:page-size="handlePageSizeChange"
      />
    </NSpace>

    <MessageDetailModal
      ref="detailModalRef"
      @changed="handleDetailChanged"
    />
  </NSpace>
</template>

// web/portal/src/pages/usercenter/components/MessageFeedPanel.tsx
/** Author: Charlie */

import { useCallback, useEffect, useState } from 'react'
import { Badge, Button, Empty, List, Pagination, Space, Spin, Tag, Typography, message } from 'antd'
import { NotificationOutlined, SoundOutlined } from '@ant-design/icons'
import { messageApi } from '@/api'
import {
  MessageDetailModal,
  type MessageDetailSource,
} from '@/components/message/MessageDetailModal'
import { useMessageUnreadStore } from '@/stores/messageUnread'
import { formatDateTime, wireBool } from '@/utils'
import { dictTypeData } from '@/utils/dict'
import { readPageMeta } from '@/utils/wire'

export function MessageFeedPanel() {
  const notifyReadAll = useMessageUnreadStore((s) => s.notifyReadAll)
  const [rows, setRows] = useState<any[]>([])
  const [total, setTotal] = useState(0)
  const [loading, setLoading] = useState(true)
  const [page, setPage] = useState(1)
  const [pageSize, setPageSize] = useState(10)
  const [detailOpen, setDetailOpen] = useState(false)
  const [detailSource, setDetailSource] = useState<MessageDetailSource | null>(null)
  const requestKey = `${page}|${pageSize}`
  const [activeKey, setActiveKey] = useState(requestKey)

  if (activeKey !== requestKey) {
    setActiveKey(requestKey)
    setLoading(true)
  }

  const applyPage = useCallback((data: any, current: number, size: number) => {
    setRows(
      (data.records ?? []).map((row: any) => ({
        ...row,
        is_read: wireBool(row.is_read ?? false),
      })),
    )
    const pageMeta = readPageMeta(data, { current, size })
    setTotal(pageMeta.total)
    if (pageMeta.current !== current) setPage(pageMeta.current)
    if (pageMeta.size !== size) setPageSize(pageMeta.size)
  }, [])

  const fetchPage = useCallback(async () => {
    setLoading(true)
    try {
      const response = await messageApi.myPage({ current: page, size: pageSize })
      applyPage(response.data ?? {}, page, pageSize)
    } finally {
      setLoading(false)
    }
  }, [applyPage, page, pageSize])

  useEffect(() => {
    let cancelled = false
    void (async () => {
      try {
        const response = await messageApi.myPage({ current: page, size: pageSize })
        if (!cancelled) applyPage(response.data ?? {}, page, pageSize)
      } finally {
        if (!cancelled) setLoading(false)
      }
    })()
    return () => {
      cancelled = true
    }
  }, [applyPage, page, pageSize])

  function kindLabel(row: any) {
    return row.kind === 'ANNOUNCEMENT' ? '公告' : '通知'
  }

  function severityLabel(row: any) {
    if (!row.severity) return ''
    return dictTypeData('NOTIFICATION_SEVERITY', row.severity) || row.severity
  }

  function excerpt(row: any) {
    const text = String(row.content || '')
      .replace(/<[^>]+>/g, ' ')
      .replace(/\s+/g, ' ')
      .trim()
    if (!text) return ''
    return text.length > 96 ? `${text.slice(0, 96)}…` : text
  }

  function openDetail(row: any) {
    setDetailSource({
      id: row.id,
      sourceType: row.kind === 'ANNOUNCEMENT' ? 'ANNOUNCEMENT' : 'NOTIFICATION',
      title: row.title,
      is_read: row.is_read,
      publish_at: row.publish_at,
      content: row.content,
      severity: row.severity,
    })
    setDetailOpen(true)
  }

  function handleDetailChanged(payload: { type: string; id: string }) {
    setRows((prev) =>
      prev.map((item) => (item.id === payload.id ? { ...item, is_read: true } : item)),
    )
  }

  async function markAllRead() {
    await messageApi.readAll()
    setRows((prev) => prev.map((row) => ({ ...row, is_read: true })))
    notifyReadAll()
    message.success('已全部标记为已读')
  }

  return (
    <Space direction="vertical" size={12} className="w-full min-w-0">
      <div className="flex justify-end gap-4">
        <Button type="link" loading={loading} onClick={() => void fetchPage()}>
          刷新
        </Button>
        <Button type="link" onClick={() => void markAllRead()}>
          全部已读
        </Button>
      </div>

      <Spin spinning={loading}>
        {!loading && !rows.length ? (
          <Empty description="暂无消息" />
        ) : (
          <List
            className="w-full min-w-0"
            dataSource={rows}
            renderItem={(row) => (
              <List.Item key={row.id} style={{ cursor: 'pointer' }} onClick={() => openDetail(row)}>
                <List.Item.Meta
                  avatar={
                    <Badge dot={!row.is_read}>
                      <div
                        className="flex h-9 w-9 items-center justify-center rounded-full"
                        style={{
                          background: 'var(--ant-color-fill-quaternary)',
                          color: row.is_read
                            ? 'var(--ant-color-text-tertiary)'
                            : 'var(--ant-color-primary)',
                        }}
                      >
                        {row.kind === 'ANNOUNCEMENT' ? <SoundOutlined /> : <NotificationOutlined />}
                      </div>
                    </Badge>
                  }
                  title={
                    <div className="flex flex-wrap items-center gap-2">
                      <Tag
                        color={row.kind === 'ANNOUNCEMENT' ? 'warning' : 'processing'}
                        className="m-0"
                      >
                        {kindLabel(row)}
                      </Tag>
                      {severityLabel(row) ? <Tag className="m-0">{severityLabel(row)}</Tag> : null}
                      <Typography.Text
                        strong={!row.is_read}
                        type={row.is_read ? 'secondary' : undefined}
                      >
                        {row.title}
                      </Typography.Text>
                      <Typography.Text type="secondary" className="text-xs whitespace-nowrap">
                        {formatDateTime(row.publish_at || row.created_at)}
                      </Typography.Text>
                    </div>
                  }
                  description={
                    excerpt(row) ? (
                      <Typography.Text type="secondary" className="text-[13px]">
                        {excerpt(row)}
                      </Typography.Text>
                    ) : null
                  }
                />
              </List.Item>
            )}
          />
        )}
      </Spin>

      {total > 0 ? (
        <div className="flex justify-end">
          <Pagination
            current={page}
            pageSize={pageSize}
            total={total}
            showSizeChanger
            pageSizeOptions={[10, 20, 30]}
            onChange={(p, size) => {
              setPage(p)
              setPageSize(size)
            }}
          />
        </div>
      ) : null}

      <MessageDetailModal
        open={detailOpen}
        source={detailSource}
        onClose={() => {
          setDetailOpen(false)
          setDetailSource(null)
        }}
        onChanged={handleDetailChanged}
      />
    </Space>
  )
}
