// web/admin/src/views/profile/components/PhonePanel.vue
<!-- Author: Charlie -->

<script setup lang="ts">
import { authApi } from '@/api'
import { useAuthStore } from '@/stores'
import { isValidPhone } from '@/utils'
import { wireBool } from '@/utils/wire'
import { encryptPasswords } from '@/utils/security'
import { computed, onMounted, onUnmounted, reactive } from 'vue'
import '../profile.css'
import BindConfirmModal from './BindConfirmModal.vue'

const OTP_COOLDOWN_SECONDS = 60
const authStore = useAuthStore()
const forceBindPhone = computed(() => Boolean(authStore.userInfo?.forceBindPhone))

const state = reactive({
  loading: false,
  savingPhone: false,
  phoneForm: {
    phone: '',
    phone_login_enabled: false,
  },
  bindConfirm: {
    show: false,
    password: '',
    otpCode: '',
    loading: false,
    sendingCode: false,
    otpCooldown: 0,
  },
})

let cooldownTimer: number | undefined

onMounted(async () => {
  await refresh()
})

onUnmounted(() => {
  if (cooldownTimer) window.clearInterval(cooldownTimer)
})

async function refresh() {
  state.loading = true
  try {
    const data = await authStore.refreshUserInfo()
    const currentProfile = data?.profile ?? {}
    state.phoneForm.phone = currentProfile.phone ?? ''
    state.phoneForm.phone_login_enabled = forceBindPhone.value
      ? true
      : wireBool(currentProfile.phone_login_enabled ?? false)
  } finally {
    state.loading = false
  }
}

function savePhone() {
  const phone = state.phoneForm.phone.trim()
  if (phone && !isValidPhone(phone)) {
    window.$message.warning('请输入有效手机号')
    return
  }
  if (!phone && (state.phoneForm.phone_login_enabled || forceBindPhone.value)) {
    window.$message.warning('请输入手机号')
    return
  }
  state.bindConfirm.password = ''
  state.bindConfirm.otpCode = ''
  state.bindConfirm.show = true
}

async function sendBindCode() {
  if (state.bindConfirm.otpCooldown > 0 || state.bindConfirm.sendingCode) return
  const phone = state.phoneForm.phone.trim()
  if (!phone || !isValidPhone(phone)) {
    window.$message.warning('请先填写有效手机号')
    return
  }
  state.bindConfirm.sendingCode = true
  try {
    await authApi.sendBindPhoneCode({ target: phone })
    window.$message.success('验证码已发送')
    state.bindConfirm.otpCooldown = OTP_COOLDOWN_SECONDS
    if (cooldownTimer) window.clearInterval(cooldownTimer)
    cooldownTimer = window.setInterval(() => {
      if (state.bindConfirm.otpCooldown <= 1) {
        state.bindConfirm.otpCooldown = 0
        if (cooldownTimer) window.clearInterval(cooldownTimer)
        return
      }
      state.bindConfirm.otpCooldown -= 1
    }, 1000)
  } finally {
    state.bindConfirm.sendingCode = false
  }
}

async function confirmBind() {
  if (!state.bindConfirm.password) {
    window.$message.warning('请输入当前密码')
    return
  }
  if (state.phoneForm.phone.trim() && !state.bindConfirm.otpCode.trim()) {
    window.$message.warning('请输入手机验证码')
    return
  }
  state.bindConfirm.loading = true
  state.savingPhone = true
  try {
    const encrypted = await encryptPasswords({ password: state.bindConfirm.password })
    await authApi.updatePhone({
      password: encrypted.values.password,
      password_key_id: encrypted.password_key_id,
      phone: state.phoneForm.phone.trim() || null,
      phone_login_enabled: forceBindPhone.value ? true : state.phoneForm.phone_login_enabled,
      otp_code: state.bindConfirm.otpCode.trim() || undefined,
    })
    state.bindConfirm.show = false
    state.bindConfirm.password = ''
    state.bindConfirm.otpCode = ''
    await refresh()
    window.$message.success('绑定已更新')
  } finally {
    state.bindConfirm.loading = false
    state.savingPhone = false
  }
}

defineExpose({ refresh })
</script>

<template>
  <NSpin :show="state.loading">
    <NAlert
      v-if="forceBindPhone"
      type="warning"
      :bordered="false"
      class="mb-12px"
      title="请先绑定手机号后才能继续使用系统"
    />
    <NForm
      class="profile-form profile-form--narrow w-full min-w-0"
      label-placement="top"
    >
      <NFormItem label="手机号">
        <NInput v-model:value="state.phoneForm.phone" />
      </NFormItem>
      <NFormItem label="启用手机号登录">
        <NSwitch
          v-model:value="state.phoneForm.phone_login_enabled"
          :disabled="forceBindPhone"
        />
      </NFormItem>
      <NFormItem :show-label="false">
        <NButton
          type="primary"
          :loading="state.savingPhone"
          @click="savePhone"
        >
          更新手机号
        </NButton>
      </NFormItem>
    </NForm>
  </NSpin>

  <BindConfirmModal
    v-model:show="state.bindConfirm.show"
    v-model:password="state.bindConfirm.password"
    v-model:otp-code="state.bindConfirm.otpCode"
    title="确认更新手机号"
    otp-label="手机验证码"
    :loading="state.bindConfirm.loading"
    :sending-code="state.bindConfirm.sendingCode"
    :otp-cooldown="state.bindConfirm.otpCooldown"
    @confirm="confirmBind"
    @send-code="sendBindCode"
  />
</template>

<style scoped>
.mb-12px {
  margin-bottom: 12px;
}
</style>

// web/portal/src/pages/usercenter/components/PhonePanel.tsx
/** Author: Charlie */

import { useCallback, useEffect, useState } from 'react'
import { Button, Form, Input, Modal, Space, Spin, Switch, Typography, message } from 'antd'
import { authApi } from '@/api'
import { useAuthStore } from '@/stores/auth'
import { encryptPasswords } from '@/utils/security'
import { isValidPhone } from '@/utils/validate'
import { wireBool } from '@/utils/wire'
import '../usercenter.css'

const OTP_COOLDOWN_SECONDS = 60

export function PhonePanel() {
  const refreshUserInfo = useAuthStore((s) => s.refreshUserInfo)
  const forceBindPhone = useAuthStore((s) => Boolean(s.userInfo?.forceBindPhone))
  const [form] = Form.useForm()
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [confirmOpen, setConfirmOpen] = useState(false)
  const [password, setPassword] = useState('')
  const [otpCode, setOtpCode] = useState('')
  const [confirmLoading, setConfirmLoading] = useState(false)
  const [sendingCode, setSendingCode] = useState(false)
  const [otpCooldown, setOtpCooldown] = useState(0)

  const applyProfile = useCallback(
    (data: any) => {
      const currentProfile = data?.profile ?? {}
      form.setFieldsValue({
        phone: currentProfile.phone ?? '',
        phone_login_enabled: forceBindPhone
          ? true
          : wireBool(currentProfile.phone_login_enabled ?? false),
      })
    },
    [form, forceBindPhone],
  )

  const refresh = useCallback(async () => {
    setLoading(true)
    try {
      applyProfile(await refreshUserInfo())
    } finally {
      setLoading(false)
    }
  }, [applyProfile, refreshUserInfo])

  useEffect(() => {
    let cancelled = false
    void (async () => {
      try {
        const data = await refreshUserInfo()
        if (!cancelled) applyProfile(data)
      } finally {
        if (!cancelled) setLoading(false)
      }
    })()
    return () => {
      cancelled = true
    }
  }, [applyProfile, refreshUserInfo])

  useEffect(() => {
    if (otpCooldown <= 0) return
    const timer = window.setTimeout(() => setOtpCooldown((v) => v - 1), 1000)
    return () => window.clearTimeout(timer)
  }, [otpCooldown])

  async function savePhone() {
    const values = await form.validateFields()
    const phone = (values.phone ?? '').trim()
    if (phone && !isValidPhone(phone)) {
      message.warning('请输入有效手机号')
      return
    }
    if (!phone && (values.phone_login_enabled || forceBindPhone)) {
      message.warning('请输入手机号')
      return
    }
    setPassword('')
    setOtpCode('')
    setConfirmOpen(true)
  }

  async function sendBindCode() {
    if (otpCooldown > 0 || sendingCode) return
    const phone = (form.getFieldValue('phone') ?? '').trim()
    if (!phone || !isValidPhone(phone)) {
      message.warning('请先填写有效手机号')
      return
    }
    setSendingCode(true)
    try {
      await authApi.sendBindPhoneCode({ target: phone })
      message.success('验证码已发送')
      setOtpCooldown(OTP_COOLDOWN_SECONDS)
    } finally {
      setSendingCode(false)
    }
  }

  async function confirmBind() {
    if (!password) {
      message.warning('请输入当前密码')
      return
    }
    const phone = (form.getFieldsValue().phone ?? '').trim()
    if (phone && !otpCode.trim()) {
      message.warning('请输入手机验证码')
      return
    }
    setConfirmLoading(true)
    setSaving(true)
    try {
      const encrypted = await encryptPasswords({ password })
      const values = form.getFieldsValue()
      await authApi.updatePhone({
        password: encrypted.values.password || '',
        password_key_id: encrypted.password_key_id,
        phone: phone || null,
        phone_login_enabled: forceBindPhone
          ? true
          : wireBool(values.phone_login_enabled ?? false),
        otp_code: otpCode.trim() || undefined,
      })
      setConfirmOpen(false)
      setPassword('')
      setOtpCode('')
      await refresh()
      message.success('绑定已更新')
    } finally {
      setConfirmLoading(false)
      setSaving(false)
    }
  }

  return (
    <>
      <Spin spinning={loading}>
        {forceBindPhone ? (
          <Typography.Paragraph type="warning">请先绑定手机号后才能继续使用系统。</Typography.Paragraph>
        ) : null}
        <Form
          form={form}
          layout="vertical"
          className="profile-form profile-form--narrow w-full min-w-0"
        >
          <Form.Item name="phone" label="手机号">
            <Input allowClear />
          </Form.Item>
          <Form.Item name="phone_login_enabled" label="启用手机号登录" valuePropName="checked">
            <Switch disabled={forceBindPhone} />
          </Form.Item>
          <Form.Item>
            <Button type="primary" loading={saving} onClick={() => void savePhone()}>
              更新手机号
            </Button>
          </Form.Item>
        </Form>
      </Spin>

      <Modal
        open={confirmOpen}
        title="确认更新手机号"
        okText="确认"
        cancelText="取消"
        confirmLoading={confirmLoading}
        maskClosable={false}
        onOk={() => void confirmBind()}
        onCancel={() => setConfirmOpen(false)}
      >
        <Form layout="vertical">
          <Form.Item label="手机验证码">
            <Space.Compact style={{ width: '100%' }}>
              <Input
                value={otpCode}
                placeholder="请输入验证码"
                onChange={(e) => setOtpCode(e.target.value)}
              />
              <Button loading={sendingCode} disabled={otpCooldown > 0} onClick={() => void sendBindCode()}>
                {otpCooldown > 0 ? `${otpCooldown}s` : '发送验证码'}
              </Button>
            </Space.Compact>
          </Form.Item>
          <Form.Item label="当前密码">
            <Input.Password
              value={password}
              placeholder="请输入当前密码"
              onChange={(e) => setPassword(e.target.value)}
              onPressEnter={() => void confirmBind()}
            />
          </Form.Item>
        </Form>
        <Typography.Text type="secondary">绑定或更换手机号需验证码与当前密码。</Typography.Text>
      </Modal>
    </>
  )
}
