// web/admin/src/views/feedback/index.vue
<!-- Author: Charlie -->

<script setup lang="ts">
import { msgFeedbackApi } from '@/api'
import { createTagColor, dictTypeColor, dictTypeData, formatDateTime } from '@/utils'
import { readPageMeta } from '@/utils/wire'
import { onMounted, reactive } from 'vue'
import { useRouter } from 'vue-router'

function renderDictTag(dictCode: string, value: string) {
  const label = dictTypeData(dictCode, value) || value
  const color = createTagColor(dictTypeColor(dictCode, value))
  return { label, color }
}

const router = useRouter()
const state = reactive({
  loading: false,
  rows: [] as any[],
  total: 0,
  page: 1,
  pageSize: 10,
})

onMounted(() => {
  void fetchPage()
})

async function fetchPage() {
  state.loading = true
  try {
    const response = await msgFeedbackApi.myPage({
      current: state.page,
      size: state.pageSize,
    })
    const data = response.data ?? {}
    state.rows = data.records ?? []
    const pageMeta = readPageMeta(data, { current: state.page, size: state.pageSize })
    state.total = pageMeta.total
    state.page = pageMeta.current
    state.pageSize = pageMeta.size
  } catch {
    state.rows = []
    state.total = 0
  } finally {
    state.loading = false
  }
}

function excerpt(content: string) {
  const text = String(content || '')
    .replace(/\s+/g, ' ')
    .trim()
  if (!text) return '点击查看详情'
  return text.length > 120 ? `${text.slice(0, 120)}…` : text
}

function goNew() {
  void router.push('/feedback/new')
}

function goDetail(id: string) {
  void router.push(`/feedback/${id}`)
}

function handlePageChange(page: number) {
  state.page = page
  void fetchPage()
}

function handlePageSizeChange(size: number) {
  state.pageSize = size
  state.page = 1
  void fetchPage()
}
</script>

<template>
  <div class="h-full min-h-0 p-4">
    <div class="mb-4 flex flex-wrap items-end justify-between gap-3">
      <div>
        <h1 class="text-xl font-semibold">
          意见反馈
        </h1>
        <p class="mt-1 text-sm text-[var(--text-color-3)]">
          提交问题与建议，并查看处理进度
        </p>
      </div>
      <NButton
        type="primary"
        @click="goNew"
      >
        <template #icon>
          <NovaIcon icon="icon-park-outline:plus" />
        </template>
        提交反馈
      </NButton>
    </div>

    <NCard
      :bordered="false"
      class="min-h-0"
    >
      <NSpin :show="state.loading">
        <NEmpty
          v-if="!state.loading && !state.rows.length"
          description="暂无反馈"
        >
          <NButton
            type="primary"
            class="mt-3"
            @click="goNew"
          >
            提交第一条反馈
          </NButton>
        </NEmpty>
        <NList
          v-else
          clickable
          show-divider
        >
          <NListItem
            v-for="item in state.rows"
            :key="item.id"
            class="cursor-pointer"
            @click="goDetail(item.id)"
          >
            <div class="flex w-full min-w-0 flex-col gap-1 py-1">
              <div class="flex flex-wrap items-center gap-2">
                <NText
                  strong
                  class="min-w-0 flex-1 truncate text-[15px]"
                >
                  {{ item.title }}
                </NText>
                <NTag
                  size="small"
                  :bordered="false"
                  :color="renderDictTag('FEEDBACK_CATEGORY', item.category).color"
                >
                  {{ renderDictTag('FEEDBACK_CATEGORY', item.category).label }}
                </NTag>
                <NTag
                  size="small"
                  :bordered="false"
                  :color="renderDictTag('FEEDBACK_STATUS', item.status).color"
                >
                  {{ renderDictTag('FEEDBACK_STATUS', item.status).label }}
                </NTag>
              </div>
              <NText
                depth="3"
                class="line-clamp-2 text-sm"
              >
                {{ excerpt(item.content) }}
              </NText>
              <NText
                depth="3"
                class="text-xs"
              >
                {{ formatDateTime(item.created_at) }}
              </NText>
            </div>
          </NListItem>
        </NList>
      </NSpin>
    </NCard>

    <div
      v-if="state.total > 0"
      class="mt-4 flex justify-end"
    >
      <NPagination
        :page="state.page"
        :page-size="state.pageSize"
        :item-count="state.total"
        :page-sizes="[10, 20, 30]"
        show-size-picker
        @update:page="handlePageChange"
        @update:page-size="handlePageSizeChange"
      />
    </div>
  </div>
</template>

// web/portal/src/pages/feedback/index.tsx
/** Author: Charlie */

import { useEffect, useState } from 'react'
import { Button, Empty, Pagination, Skeleton } from 'antd'
import { PlusOutlined } from '@ant-design/icons'
import { Link } from 'react-router-dom'
import { feedbackApi } from '@/api'
import { DictTag } from '@/components/common/DictTag'
import { formatDateTime } from '@/utils/time'
import { readPageMeta } from '@/utils/wire'

export function FeedbackListPage() {
  const [loading, setLoading] = useState(true)
  const [records, setRecords] = useState<any[]>([])
  const [total, setTotal] = useState(0)
  const [current, setCurrent] = useState(1)
  const [size, setSize] = useState(10)

  useEffect(() => {
    let mounted = true

    async function load() {
      setLoading(true)
      try {
        const res = await feedbackApi.myPage({ current, size })
        if (!mounted) return
        setRecords(res.data.records ?? [])
        setTotal(readPageMeta(res.data).total)
      } catch {
        if (!mounted) return
        setRecords([])
        setTotal(0)
      } finally {
        if (mounted) setLoading(false)
      }
    }

    void load()
    return () => {
      mounted = false
    }
  }, [current, size])

  return (
    <div className="page-shell">
      <div className="mb-4 flex flex-wrap items-end justify-between gap-3">
        <div>
          <h1 className="text-xl font-semibold">意见反馈</h1>
          <p className="muted-text mt-1 text-sm">提交问题与建议，并查看处理进度</p>
        </div>
        <Link to="/feedback/new">
          <Button type="primary" icon={<PlusOutlined />}>
            提交反馈
          </Button>
        </Link>
      </div>

      <section className="panel overflow-hidden">
        <Skeleton active loading={loading} paragraph={{ rows: 6 }}>
          {records.length ? (
            <div>
              {records.map((item) => (
                <Link
                  key={item.id}
                  to={`/feedback/${item.id}`}
                  className="flex flex-col border-b border-[var(--ant-color-border)] px-4 py-4 last:border-b-0 transition-colors hover:bg-[var(--ant-color-fill-quaternary)]"
                >
                  <div className="flex flex-wrap items-center gap-2">
                    <div className="min-w-0 flex-1 truncate text-[15px] font-medium">
                      {item.title}
                    </div>
                    <DictTag dictCode="FEEDBACK_CATEGORY" value={item.category} />
                    <DictTag dictCode="FEEDBACK_STATUS" value={item.status} />
                  </div>
                  <div className="muted-text mt-1 line-clamp-2 text-sm">
                    {String(item.content || '')
                      .replace(/\s+/g, ' ')
                      .trim()
                      .slice(0, 120) || '点击查看详情'}
                  </div>
                  <div className="muted-text mt-2 text-xs">{formatDateTime(item.created_at)}</div>
                </Link>
              ))}
            </div>
          ) : !loading ? (
            <div className="py-16">
              <Empty description="暂无反馈">
                <Link to="/feedback/new">
                  <Button type="primary">提交第一条反馈</Button>
                </Link>
              </Empty>
            </div>
          ) : null}
        </Skeleton>
      </section>

      {total > 0 ? (
        <div className="mt-4 flex justify-end">
          <Pagination
            current={current}
            pageSize={size}
            total={total}
            showSizeChanger
            showTotal={(t) => `共 ${t} 条`}
            onChange={(page, pageSize) => {
              setCurrent(page)
              setSize(pageSize)
            }}
          />
        </div>
      ) : null}
    </div>
  )
}
