// web/portal/src/pages/feedback/detail.tsx
/** Author: Charlie */

import { useEffect, useMemo, useState } from 'react'
import { Button, Empty, Image, Skeleton, Typography } from 'antd'
import { ArrowLeftOutlined } from '@ant-design/icons'
import { Link, useParams } from 'react-router-dom'
import { feedbackApi } from '@/api'
import { DictTag } from '@/components/common/DictTag'
import { displayValue, formatDateTime, formatFileSize, isImageFile } from '@/utils'

export function FeedbackDetailPage() {
  const { id } = useParams<{ id: string }>()
  const [loading, setLoading] = useState(Boolean(id))
  const [detail, setDetail] = useState<any>(null)
  const [notFound, setNotFound] = useState(!id)
  const [activeId, setActiveId] = useState(id)

  if (id !== activeId) {
    setActiveId(id)
    setLoading(Boolean(id))
    setNotFound(!id)
    setDetail(null)
  }

  useEffect(() => {
    if (!id) return

    let mounted = true

    void (async () => {
      try {
        const res = await feedbackApi.myDetail(id)
        if (!mounted) return
        setDetail(res.data ?? null)
        setNotFound(!res.data)
      } catch {
        if (!mounted) return
        setDetail(null)
        setNotFound(true)
      } finally {
        if (mounted) setLoading(false)
      }
    })()

    return () => {
      mounted = false
    }
  }, [id])

  const attachments = useMemo(() => {
    const list = detail?.attachments
    return Array.isArray(list) ? list : []
  }, [detail])

  if (loading) {
    return (
      <div className="page-shell">
        <Skeleton active paragraph={{ rows: 8 }} />
      </div>
    )
  }

  if (notFound || !detail) {
    return (
      <div className="page-shell">
        <Empty description="反馈不存在或无权查看" />
        <div className="mt-4 text-center">
          <Link to="/feedback">
            <Button type="primary">返回反馈列表</Button>
          </Link>
        </div>
      </div>
    )
  }

  return (
    <div className="page-shell">
      <div className="mb-4">
        <Link to="/feedback">
          <Button type="text" icon={<ArrowLeftOutlined />} className="!px-0">
            返回反馈列表
          </Button>
        </Link>
      </div>

      <div className="rounded-lg border border-[var(--ant-color-border)] bg-[var(--ant-color-bg-container)] p-5">
        <div className="mb-3 flex flex-wrap items-center gap-2">
          <Typography.Title level={3} className="!mb-0 !text-xl">
            {displayValue(detail.title)}
          </Typography.Title>
          <DictTag dictCode="FEEDBACK_STATUS" value={detail.status} />
          <DictTag dictCode="FEEDBACK_TYPE" value={detail.type} />
        </div>
        <Typography.Paragraph type="secondary" className="!mb-4 text-xs">
          提交于 {formatDateTime(detail.created_at)}
        </Typography.Paragraph>
        <Typography.Paragraph className="whitespace-pre-wrap">
          {displayValue(detail.content)}
        </Typography.Paragraph>

        {attachments.length ? (
          <div className="mt-4">
            <Typography.Text strong>附件</Typography.Text>
            <div className="mt-2 flex flex-wrap gap-3">
              {attachments.map((file: any) => {
                const url = file.url || file.file_url
                const name = file.name || file.filename || '附件'
                if (isImageFile(name) || isImageFile(url)) {
                  return (
                    <Image
                      key={file.id || url || name}
                      src={url}
                      alt={name}
                      width={96}
                      height={96}
                      className="rounded object-cover"
                    />
                  )
                }
                return (
                  <a
                    key={file.id || url || name}
                    href={url}
                    target="_blank"
                    rel="noreferrer"
                    className="text-sm"
                  >
                    {name}
                    {file.size ? ` (${formatFileSize(file.size)})` : ''}
                  </a>
                )
              })}
            </div>
          </div>
        ) : null}

        {detail.reply_content ? (
          <div className="mt-6 rounded border border-[var(--ant-color-border-secondary)] bg-[var(--ant-color-fill-quaternary)] p-4">
            <Typography.Text strong>官方回复</Typography.Text>
            <Typography.Paragraph className="mt-2 mb-0 whitespace-pre-wrap">
              {displayValue(detail.reply_content)}
            </Typography.Paragraph>
            {detail.replied_at ? (
              <Typography.Text type="secondary" className="text-xs">
                回复于 {formatDateTime(detail.replied_at)}
              </Typography.Text>
            ) : null}
          </div>
        ) : null}
      </div>
    </div>
  )
}

// web/admin/src/views/feedback/detail.vue
<!-- Author: Charlie -->

<script setup lang="ts">
import { sysFeedbackApi } from '@/api'
import {
  createTagColor,
  dictTypeColor,
  dictTypeData,
  displayValue,
  formatDateTime,
  formatFileSize,
  isImageFile,
} from '@/utils'
import { computed, onMounted, reactive, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'

function renderDictTag(dictCode: string, value: string) {
  const label = dictTypeData(dictCode, value) || value
  const color = createTagColor(dictTypeColor(dictCode, value))
  return { label, color }
}

const route = useRoute()
const router = useRouter()
const state = reactive({
  loading: false,
  detail: null as any,
  notFound: false,
})

const dataId = computed(() => {
  const id = route.params.id
  return typeof id === 'string' ? id : ''
})

const attachments = computed(() => {
  const list = state.detail?.attachments
  if (Array.isArray(list) && list.length) return list
  return (state.detail?.attach_object_names || []).map((object_name: string) => ({
    object_name,
    original_name: object_name,
    url: null,
  }))
})

async function fetchDetail(id: string) {
  if (!id) {
    state.notFound = true
    state.detail = null
    return
  }
  state.loading = true
  state.notFound = false
  try {
    const response = await sysFeedbackApi.myDetail(id)
    state.detail = response.data ?? null
    if (!state.detail) state.notFound = true
  } catch {
    state.detail = null
    state.notFound = true
  } finally {
    state.loading = false
  }
}

function goBack() {
  void router.push('/feedback')
}

function attachmentLabel(item: any) {
  return item.original_name || item.object_name || '附件'
}

onMounted(() => {
  void fetchDetail(dataId.value)
})
watch(dataId, (id) => {
  void fetchDetail(id)
})
</script>

<template>
  <div class="h-full min-h-0 p-4">
    <div class="mb-4">
      <NButton
        text
        @click="goBack"
      >
        <template #icon>
          <NovaIcon icon="icon-park-outline:left" />
        </template>
        返回我的反馈
      </NButton>
    </div>

    <NCard
      :bordered="false"
      class="max-w-4xl"
    >
      <NSpin :show="state.loading">
        <NEmpty
          v-if="state.notFound"
          description="反馈不存在或无权查看"
        >
          <NButton
            type="primary"
            class="mt-3"
            @click="goBack"
          >
            返回列表
          </NButton>
        </NEmpty>
        <article v-else-if="state.detail">
          <h1 class="text-xl font-semibold md:text-2xl">
            {{ displayValue(state.detail.title) }}
          </h1>
          <div class="mt-3 flex flex-wrap items-center gap-2">
            <NTag
              size="small"
              :bordered="false"
              :color="renderDictTag('FEEDBACK_CATEGORY', state.detail.category).color"
            >
              {{ renderDictTag('FEEDBACK_CATEGORY', state.detail.category).label }}
            </NTag>
            <NTag
              size="small"
              :bordered="false"
              :color="renderDictTag('FEEDBACK_STATUS', state.detail.status).color"
            >
              {{ renderDictTag('FEEDBACK_STATUS', state.detail.status).label }}
            </NTag>
            <NText
              depth="3"
              class="text-xs"
            >
              提交于 {{ formatDateTime(state.detail.created_at) }}
            </NText>
          </div>

          <div class="mt-6 grid gap-3 text-sm md:grid-cols-2">
            <div>
              <div class="mb-1 text-[var(--text-color-3)]">
                联系方式
              </div>
              <div>{{ displayValue(state.detail.contact) }}</div>
            </div>
          </div>

          <div class="mt-6 border-t border-[var(--border-color)] pt-6">
            <div class="mb-2 text-sm font-medium">
              内容
            </div>
            <div class="whitespace-pre-wrap text-sm leading-7">
              {{ displayValue(state.detail.content) }}
            </div>
          </div>

          <div
            v-if="attachments.length"
            class="mt-6 border-t border-[var(--border-color)] pt-6"
          >
            <div class="mb-3 text-sm font-medium">
              附件
            </div>
            <div class="flex flex-wrap gap-3">
              <template
                v-for="item in attachments"
                :key="item.object_name || attachmentLabel(item)"
              >
                <div
                  v-if="item.url && isImageFile(item)"
                  class="w-28"
                >
                  <NImage
                    :src="item.url"
                    :alt="attachmentLabel(item)"
                    width="112"
                    height="112"
                    object-fit="cover"
                    style="border-radius: 8px"
                  />
                  <div class="mt-1 truncate text-xs">
                    {{ attachmentLabel(item) }}
                  </div>
                </div>
                <a
                  v-else
                  class="rounded border border-[var(--border-color)] px-3 py-2 text-sm"
                  :href="item.url || undefined"
                  target="_blank"
                  rel="noreferrer"
                >
                  {{ attachmentLabel(item) }}
                  <template v-if="item.size != null">（{{ formatFileSize(item.size) }}）</template>
                </a>
              </template>
            </div>
          </div>

          <div
            v-if="state.detail.reply"
            class="mt-6 rounded-lg border border-[var(--border-color)] bg-[var(--hover-color)] p-4"
          >
            <div class="mb-2 text-sm font-medium">
              官方回复
            </div>
            <div class="whitespace-pre-wrap text-sm leading-7">
              {{ state.detail.reply }}
            </div>
            <div
              v-if="state.detail.replied_at"
              class="mt-2 text-xs text-[var(--text-color-3)]"
            >
              回复于 {{ formatDateTime(state.detail.replied_at) }}
            </div>
          </div>
        </article>
      </NSpin>
    </NCard>
  </div>
</template>
